<a href="https://colab.research.google.com/github/DrSubbiah/1.Bayesian-Inference/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

# Creating arrays with initial values
zeros = np.zeros((3, 3))  # 3x3 array of zeros
ones = np.ones((2, 4))    # 2x4 array of ones
print(zeros)
print(ones)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Basic arithmetic operations
array_sum = array_1d + 10
print(array_sum)  # Output: [11 12 13 14 15]

array_product = array_1d * 2
print(array_product)  # Output: [2 4 6 8 10]

# Element-wise operations
array_diff = array_1d - array_product
print(array_diff)  # Output: [-1  0  1  2  3]

array_square = array_1d ** 2
print(array_square)  # Output: [ 1  4  9 16 25]


[11 12 13 14 15]
[ 2  4  6  8 10]
[-1 -2 -3 -4 -5]
[ 1  4  9 16 25]


In [ ]:
# Indexing
element = array_1d[2]
print(element)  # Output: 3

# Slicing
sub_array = array_1d[1:4]
print(sub_array)  # Output: [2 3 4]

# Advanced slicing
reverse_array = array_1d[::-1]
print(reverse_array)  # Output: [5 4 3 2 1]


3
[2 3 4]
[5 4 3 2 1]


In [ ]:
# Matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print(matrix_product)  # Output: [[19 22]
                       #          [43 50]]

# Transpose of a matrix
transpose = np.transpose(matrix_a)
print(transpose)  # Output: [[1 3]
                       #          [2 4]]


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
# Basic statistical operations
mean = np.mean(array_1d)
median = np.median(array_1d)
std_dev = np.std(array_1d)
sum_total = np.sum(array_1d)

print(mean)      # Output: 3.0
print(median)    # Output: 3.0
print(std_dev)   # Output: 1.4142135623730951
print(sum_total) # Output: 15


3.0
3.0
1.4142135623730951
15


In [ ]:
# Generating random numbers
random_array = np.random.rand(3, 3)
print(random_array)

random_integers = np.random.randint(0, 10, size=(3, 3))
print(random_integers)


[[0.11180205 0.07115739 0.41047548]
 [0.31107842 0.26434933 0.66960427]
 [0.87993285 0.31305548 0.39945456]]
[[5 8 7]
 [9 5 8]
 [0 5 7]]
